#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  merge-default-rules: true
  formatter: tap
files:
  include: 'fiba/**/*.s+(a|c)ss'
  ignore:
    - 'fiba/play/ui/reset.scss'
    - 'fiba/play/ui/_viewports.scss'
rules:
  attribute-quotes:
    - 2
    - include: true
  bem-depth:    # NOTE: We can enforce our custom bem depth in `class-name-format` regex
    - 2
    - max-depth: 1
  border-zero:
    - 2
    - convention: none
  brace-style:
    - 2
    - style: 1tbs
  class-name-format:
    - 2
    - allow-leading-underscore: false   # FIXME: discuss
      # BEM in PascalCase with kebab-case modifier
      # FIXME: We can do the bem-depth here by restricting the second part to just one like this:
      # ^[A-Z][a-z0-9]+([A-Z][a-z0-9]+)*(-[A-Z][a-z0-9]+([A-Z][a-z0-9]+)*)?(--[a-z][\-a-z0-9]*)*$
      convention: ^[A-Z][a-z0-9]+([A-Z][a-z0-9]+)*(-[A-Z][a-z0-9]+([A-Z][a-z0-9]+)*)?(--[a-z][\-a-z0-9]*)*$
      convention-explanation: "Class must be PascalCase version of BEM with optional kebab-case modifier. Examples: 'FooBar', 'FooBar-FazBaz', 'Foobar--disabled'"
  # FIXME: discuss @see https://github.com/sasstools/sass-lint/blob/master/docs/rules/clean-import-paths.md
  clean-import-paths: 2
  empty-line-between-blocks: 2
  extends-before-declarations: 2
  extends-before-mixins: 2
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format: 2
  hex-length:
    - 2
    - style: long
  hex-notation: 2
  id-name-format: 2
  indentation: 2
  leading-zero: 0
  mixin-name-format: 2
  mixins-before-declarations:
    - 2
    - exclude: [viewports, transform, prefixer]   # Add other prefixable bourbon mixins
  nesting-depth:
    - 2
    - max-depth: 5
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 2
  no-color-literals: 0    # FIXME: discuss
  no-combinators: 0
  no-css-comments: 0
  no-debug: 2
  no-disallowed-properties: 0
  no-duplicate-properties:
    - 2
    - exclude: [background-color, src]
  no-empty-rulesets: 2
  no-extends: 0k
  no-ids: 1
  no-important: 1
  no-invalid-hex: 2
  no-mergeable-selectors: 0
  no-misspelled-properties: 2
  no-qualifying-elements:
    - 2
    - allow-element-with-attribute: true
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 2
  no-universal-selectors: 2
  no-url-protocols: 2
  no-vendor-prefixes: 2   # NOTE: Prefer bourbon helpers
  no-warn: 2              # NOTE: prefer @error
  one-declaration-per-line: 2
  placeholder-in-extend: 0
  placeholder-name-format: 2
  property-sort-order:
    - 2
    - order: smacss
  property-units: 0
  pseudo-element: 0
  quotes: 2
  shorthand-values: 2
  single-line-per-selector: 0
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 2
  trailing-semicolon: 2
  url-quotes: 2
  variable-name-format:
    - 2
    - convention: ^(([a-z][\-a-z0-9]*)|([A-Z][_A-Z0-9]*))$
      convention-explanation: 'Variables must consist of either hyphenated lowercase letters ($foo-bar) or uppercase letters with underscores ($FOO_BAR)'
  zero-unit: 2
